DungeonHeros/Controllers/MessageController.cs
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DungeonHeros.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using DbContext = DungeonHeros.Models.DbContext;

namespace DungeonHeros.Controllers
{
    public class MessageController : Controller
    {
        private readonly DbContext _dbContext;
        private readonly UserManager<User> _manager;
        public MessageController([FromServices] DbContext dbContext, UserManager<User> manager)
        {
            _dbContext = dbContext;
            _manager = manager;
        }
        
        private User GetCurrentUser()
        {
            var t = _manager.GetUserId(HttpContext.User);
            return GetUserById(t);
        }
        
        private User GetUserById(string id) => 
            _dbContext.Users.Include(h => h.Hero).Single(u => u.Id == id);

        private Hero GetMessageById(int id) =>
            _dbContext.Heroes.Include(h => h.Messages).Single(m => m.HeroId == id);

        [Authorize]
        public IActionResult Messages()
        {
            var id = GetCurrentUser().Hero.HeroId;
            var messages = GetMessageById(id);
            return View(messages);
        }
        
        [Authorize(Roles = "Admin")]
        public IActionResult SendMessage(int id)
        {
            ViewData["TeamId"] = id;
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> SendMessage(int teamId, string title, string message)
        {
            var currentTeam = GetTeamById(teamId);

            _dbContext.Add(new Message {MessageContent = message, MessageTitle = title, Heroes = currentTeam.Heroes});
            await _dbContext.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

        private Team GetTeamById(int id) => _dbContext.Teams.Include(h => h.Heroes).Single(t => t.TeamId == id);
    }
}

DungeonHeros/Controllers/UserController.cs
using System.Linq;
using System.Threading.Tasks;
using DungeonHeros.Models;
using DungeonHeros.Models.Factory.User;
using DungeonHeros.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using DbContext = DungeonHeros.Models.DbContext;

namespace DungeonHeros.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly DbContext _dbContext;
        private readonly UserManager<User> _manager;
        private readonly IUserFactory _factory;

        public UserController([FromServices] DbContext dbContext, UserManager<User> manager)
        {
            _dbContext = dbContext;
            _manager = manager;
            _factory = new UserFactory();
        }

        public IActionResult ProfileModification()
        {
            var hero = GetCurrentUser().Hero;
            return View(hero);
        }
        
        
        [HttpPost, AutoValidateAntiforgeryToken]
        public async Task<IActionResult> ProfileModification(UserModificationViewModel viewModel)
        {
            var user = GetCurrentUser();
            if (!ModelState.IsValid) return View(user.Hero);
            
            var updateUser = _factory.UpdateUser(user, viewModel.Name, viewModel.ImagePath);
            _dbContext.Update(updateUser);
            await _dbContext.SaveChangesAsync();
            return RedirectToAction("Index", "Home");

        }
        
        private User GetCurrentUser()
        {
            var t = _manager.GetUserId(HttpContext.User);
            return GetUserById(t);

        }
        
        
        /**
         * Retourne l'utilisateur sur base de son ID.
         */
        private User GetUserById(string id) => _dbContext.Users.Include(h => h.Hero).Single(u => u.Id == id);
        
    }
}

DungeonHeros/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - DungeonHeros</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
</head>

<body>
<header>
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg bg-black fixed-top">
            <div class="container-fluid">
                <img src="~/assets/img/myLogo.png" width="40px" height="40px" alt="logo.png">
                <a class="navbar-brand mainTitle m-md-2 navTitle" asp-action="Index" asp-controller="Home">Dungeon Hero's</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#main_nav"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="main_nav">
                    <ul class="navbar-nav">
                        <li class="nav-item active mainTitle">
                            <a class="mainTitle nav-link" asp-action="Index" asp-protocol="#lead" asp-controller="Home">Game</a>
                        </li>
                        <li class="nav-item active mainTitle">
                            <a class="mainTitle nav-link" asp-action="Index" asp-controller="Home">Studio</a>
                        </li>
                        @if (!SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item pe-3">
                                <a class="mainTitle nav-link" asp-area="Identity" asp-page="/Account/Register">Start the adventure</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>

            <!-- Barre à dérouler -->
            <nav class="navbar navbar-light bg-black">
                <div class="btn-group dropstart">
                    <a type="button" class="btn btn-secondary navBtnColor" data-bs-toggle="dropdown" aria-expanded="false">
                        <img id="" href="#" src="~/assets/justify.svg" alt="" width="30" height="24">
                    </a>
                    <ul class="dropdown-menu dropdown-menu-light" aria-labelledby="navbarDarkDropdownMenuLink">
                        <li class="dropdown-item" asp-action="ProfileModification">
                            <a asp-action="ProfileModification" asp-controller="User" class="dropdownItems">
                                <img id="" asp-action="ProfileModification"
                                     src="~/assets/person-fill.svg" alt="" width="30"
                                     height="24" class="m-lg-2">Profile
                            </a>
                        </li>
                        <li class="dropdown-item">
                            <a asp-action="Teams" asp-controller="Teams" class="dropdownItems">
                                <img id=""
                                     src="~/assets/person-lines-fill.svg" alt="" width="30"
                                     height="24" class="m-lg-2">Teams
                            </a>
                        </li>
                        <li class="dropdown-item">
                            <a asp-controller="Message" asp-action="Messages" class="dropdownItems">
                                <img id="" href="#"
                                     src="~/assets/chat-right-dots-fill.svg" alt="" width="30"
                                     height="24" class="m-lg-2">Messages
                            </a>
                        </li>
                        <li class="dropdown-item">
                            <a asp-action="Dungeons" asp-controller="Dungeons" class="dropdownItems">
                                <img id="" href="#"
                                     src="~/assets/dungeon.svg" alt="" width="30"
                                     height="24" class="m-lg-2">Dungeons
                            </a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="dropdown-item">
                                <a asp-action="Bestiary" asp-controller="Bestiary" class="dropdownItems">
                                    <img id="" href="#"
                                         src="~/assets/monsters.svg" alt="" width="30"
                                         height="24" class="m-lg-2">Bestiary
                                </a>
                            </li>  
                        }
                        <li class="dropdown-item">
                            <partial name="_LoginPartial"/>
                        </li>
                    </ul>
                </div>
            </nav>
        </nav>
    </div>
</header>
@RenderBody()
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
<script>
  AOS.init();
</script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>